package operationsvc

import (
	"context"
	"encoding/json"
	"errors"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/dylanLi233/switch-manager/internal/apperror"
	"github.com/dylanLi233/switch-manager/internal/concurrency"
	"github.com/dylanLi233/switch-manager/internal/domain/audit"
	"github.com/dylanLi233/switch-manager/internal/domain/auth"
	"github.com/dylanLi233/switch-manager/internal/domain/device"
	"github.com/dylanLi233/switch-manager/internal/domain/operation"
	"github.com/dylanLi233/switch-manager/internal/domain/task"
	"github.com/dylanLi233/switch-manager/pkg/pluginapi"
)

type memoryTasks struct{ mu sync.Mutex; values map[string]task.Persisted }
func newMemoryTasks()*memoryTasks{return &memoryTasks{values:map[string]task.Persisted{}}}
func(r *memoryTasks)Create(_ context.Context,v task.Persisted)(task.Persisted,error){r.mu.Lock();defer r.mu.Unlock();for _,x:=range r.values{if v.IdempotencyKey!=""&&x.CreatedBy==v.CreatedBy&&x.IdempotencyKey==v.IdempotencyKey{return task.Persisted{},apperror.New(apperror.CodeIdempotencyConflict,"")}};r.values[v.ID]=v;return v,nil}
func(r *memoryTasks)Get(_ context.Context,id string)(task.Persisted,error){r.mu.Lock();defer r.mu.Unlock();v,ok:=r.values[id];if !ok{return task.Persisted{},apperror.New(apperror.CodeTaskNotFound,"")};return v,nil}
func(r *memoryTasks)FindByIdempotency(_ context.Context,user,key string)(task.Persisted,error){r.mu.Lock();defer r.mu.Unlock();for _,v:=range r.values{if v.CreatedBy==user&&v.IdempotencyKey==key{return v,nil}};return task.Persisted{},apperror.New(apperror.CodeTaskNotFound,"")}
func(r *memoryTasks)Save(_ context.Context,v task.Persisted,_ int64)(task.Persisted,error){r.mu.Lock();defer r.mu.Unlock();r.values[v.ID]=v;return v,nil}
func(r *memoryTasks)ListRecoverable(context.Context,int)([]task.Persisted,error){return nil,nil}
func(r *memoryTasks)QueuePending(_ context.Context,id string)(task.Persisted,error){r.mu.Lock();defer r.mu.Unlock();v:=r.values[id];v.Status=task.StatusQueued;v.Version++;r.values[id]=v;return v,nil}
func(r *memoryTasks)RequestCancel(_ context.Context,id string,at time.Time)(task.Persisted,error){r.mu.Lock();defer r.mu.Unlock();v:=r.values[id];v.Status=task.StatusCancelled;v.FinishedAt=&at;v.CancelRequestedAt=&at;v.Version++;r.values[id]=v;return v,nil}
func(r *memoryTasks)ClaimNextQueued(context.Context,time.Time)(task.Persisted,error){return task.Persisted{},task.ErrNoQueuedTask}
func(r *memoryTasks)InterruptRunning(context.Context,time.Time)(int64,error){return 0,nil}

type memoryCommitter struct{tasks *memoryTasks;audits *memoryAudits}
func(c memoryCommitter)CreateTaskAndAudit(ctx context.Context,value task.Persisted,record audit.Record)(task.Persisted,error){if c.audits.failCreate{return task.Persisted{},apperror.Wrap(apperror.CodeAuditUnavailable,"",errors.New("audit down"))};created,err:=c.tasks.Create(ctx,value);if err!=nil{return task.Persisted{},err};if _,err:=c.audits.Create(ctx,record);err!=nil{c.tasks.mu.Lock();delete(c.tasks.values,value.ID);c.tasks.mu.Unlock();return task.Persisted{},apperror.Wrap(apperror.CodeAuditUnavailable,"",err)};return created,nil}

type memoryAudits struct{mu sync.Mutex;values map[string]audit.Record;failCreate,failComplete bool}
func newMemoryAudits()*memoryAudits{return &memoryAudits{values:map[string]audit.Record{}}}
func(a *memoryAudits)Create(_ context.Context,v audit.Record)(audit.Record,error){if a.failCreate{return audit.Record{},errors.New("audit down")};a.mu.Lock();defer a.mu.Unlock();a.values[v.ID]=v;return v,nil}
func(a *memoryAudits)Get(_ context.Context,id string)(audit.Record,error){a.mu.Lock();defer a.mu.Unlock();return a.values[id],nil}
func(a *memoryAudits)Complete(_ context.Context,id,status,code string,result json.RawMessage,at time.Time)(audit.Record,error){if a.failComplete{return audit.Record{},errors.New("audit down")};a.mu.Lock();defer a.mu.Unlock();v:=a.values[id];v.Status=status;v.ErrorCode=code;v.ResultSummaryRedacted=result;v.FinishedAt=&at;a.values[id]=v;return v,nil}

type oneDevice struct{value device.Device}
func(d oneDevice)Get(context.Context,string)(device.Device,error){return d.value,nil}
type testPlugin struct{}
func(testPlugin)Metadata()pluginapi.Metadata{return pluginapi.Metadata{Name:"test-plugin",Vendor:pluginapi.VendorHuawei,PluginVersion:pluginapi.Version{Major:1},SDKVersion:pluginapi.Version{Major:1},Operations:[]pluginapi.OperationName{"configuration.echo","diagnostic.echo",SaveConfigOperation}}}
func(testPlugin)Detect(context.Context,pluginapi.CLISession)(pluginapi.DeviceInfo,error){return pluginapi.DeviceInfo{},nil}
func(testPlugin)Capabilities(context.Context,pluginapi.DeviceInfo)(pluginapi.CapabilitySet,error){return pluginapi.NewCapabilitySet()}
func(testPlugin)BuildPlan(_ context.Context,r pluginapi.PlanRequest)(pluginapi.ExecutionPlan,error){text:="main";if r.Operation==SaveConfigOperation{text="save"};return pluginapi.ExecutionPlan{PlanID:r.PlanID,DeviceID:r.DeviceID,Vendor:r.Device.Vendor,PluginName:"test-plugin",PluginVersion:"1.0.0",Operation:r.Operation,Class:r.Class,SaveConfig:r.SaveConfig,RiskLevel:pluginapi.RiskMedium,Commands:[]pluginapi.PlannedCommand{{Sequence:1,Text:text,Timeout:time.Second}}},nil}
func(testPlugin)ParseResult(_ context.Context,_ pluginapi.ExecutionPlan,tr pluginapi.Transcript)(pluginapi.OperationResult,error){result:=pluginapi.OperationResult{Status:pluginapi.ResultSuccess,StartedAt:tr.StartedAt,FinishedAt:tr.FinishedAt,Data:map[string]any{"ok":true}};for _,record:=range tr.Commands{result.Commands=append(result.Commands,pluginapi.CommandExecution{Sequence:record.Sequence,Succeeded:record.Succeeded,ErrorCode:record.ErrorCode,Duration:record.Duration});if !record.Succeeded{result.Status=pluginapi.ResultFailed;result.ErrorCode=record.ErrorCode}};return result,nil}
type testRegistry struct{plugin pluginapi.Plugin}
func(r testRegistry)Resolve(pluginapi.Vendor)(pluginapi.Plugin,error){return r.plugin,nil}
func(r testRegistry)LookupCapability(_ context.Context,_ pluginapi.Vendor,_ pluginapi.DeviceInfo,name pluginapi.OperationName)(pluginapi.Capability,error){return pluginapi.Capability{Operation:name,Level:pluginapi.SupportSupported},nil}
type queueStub struct{repo *memoryTasks;complete bool;calls int}
func(q *queueStub)Queue(ctx context.Context,id string)(task.Persisted,error){q.calls++;v,_:=q.repo.QueuePending(ctx,id);if q.complete{v.Status=task.StatusSuccess;v.Result=json.RawMessage(`{"ok":true}`);v.Version++;q.repo.mu.Lock();q.repo.values[id]=v;q.repo.mu.Unlock()};return v,nil}
type sessionStub struct{failSave bool}
func(s *sessionStub)Execute(_ context.Context,c pluginapi.PlannedCommand)(pluginapi.CommandOutput,error){if c.Text=="save"&&s.failSave{return pluginapi.CommandOutput{Output:"partial"},errors.New("save failed")};return pluginapi.CommandOutput{Output:"ok",Duration:time.Millisecond},nil}
func(s *sessionStub)Close()error{return nil}
type factoryStub struct{mu sync.Mutex;opens int;failSave bool}
func(f *factoryStub)Open(context.Context,device.Device)(Session,error){f.mu.Lock();f.opens++;f.mu.Unlock();return &sessionStub{failSave:f.failSave},nil}
func actor()auth.Actor{return auth.Actor{UserID:"user",Username:"alice",Role:auth.RoleAdmin}}
func request(mode operation.ExecutionMode,dry,save bool)SubmitRequest{return SubmitRequest{RequestID:"req",Operation:operation.Request{Name:"configuration.echo",Class:operation.ClassConfig,DeviceID:"device",Parameters:map[string]any{"message":"hello"},ExecutionMode:mode,DryRun:dry,SaveConfig:save,Actor:actor()}}}
func setup(t *testing.T)(*Planner,*memoryTasks,*memoryAudits){t.Helper();now:=time.Now().UTC();planner,err:=NewPlanner(oneDevice{device.Device{ID:"device",Name:"test",Host:"192.0.2.1",SSHPort:22,CredentialID:"credential",Vendor:device.VendorHuawei,Model:"FAKE-SW",DetectMode:device.DetectModeAuto,Status:device.StatusActive,IdentityStatus:device.IdentityVerified,CreatedAt:now,UpdatedAt:now}},testRegistry{testPlugin{}});if err!=nil{t.Fatal(err)};return planner,newMemoryTasks(),newMemoryAudits()}
func newTestService(tasks *memoryTasks,audits *memoryAudits,planner *Planner,queue Queue,config Config)*Service{service,err:=NewService(tasks,audits,planner,queue,memoryCommitter{tasks,audits},config);if err!=nil{panic(err)};return service}

func TestConfigAuditFailureRollsBackBeforeQueue(t *testing.T){planner,tasks,audits:=setup(t);audits.failCreate=true;queue:=&queueStub{repo:tasks};service:=newTestService(tasks,audits,planner,queue,Config{});ids:=[]string{"task","plan"};service.ids=func()(string,error){id:=ids[0];ids=ids[1:];return id,nil};submission,err:=service.Submit(context.Background(),request(operation.ExecutionModeAsync,false,false));if !apperror.IsCode(err,apperror.CodeAuditUnavailable){t.Fatalf("err=%v",err)};if _,getErr:=tasks.Get(context.Background(),"task");!apperror.IsCode(getErr,apperror.CodeTaskNotFound){t.Fatalf("task survived atomic rollback: %v",getErr)};if queue.calls!=0||submission.Task.ID!=""{t.Fatalf("calls=%d submission=%+v",queue.calls,submission)}}
func TestSyncAndAsyncBothCreateTasks(t *testing.T){planner,tasks,audits:=setup(t);queue:=&queueStub{repo:tasks,complete:true};service:=newTestService(tasks,audits,planner,queue,Config{SyncWaitTimeout:time.Second,WaitPollInterval:time.Millisecond});n:=0;service.ids=func()(string,error){n++;return []string{"task-sync","plan-sync","task-async","plan-async"}[n-1],nil};syncSub,err:=service.Submit(context.Background(),request(operation.ExecutionModeSync,false,false));if err!=nil||!syncSub.Completed{t.Fatalf("sync=%+v err=%v",syncSub,err)};asyncSub,err:=service.Submit(context.Background(),request(operation.ExecutionModeAsync,false,false));if err!=nil||asyncSub.Task.ID!="task-async"{t.Fatalf("async=%+v err=%v",asyncSub,err)};if len(tasks.values)!=2{t.Fatalf("task count=%d",len(tasks.values))}}
func TestDryRunExecutorDoesNotOpenSession(t *testing.T){planner,_,audits:=setup(t);factory:=&factoryStub{};guard,_:=concurrency.NewController(5);executor,_:=NewExecutor(planner,audits,factory,guard);snapshot:=snapshotRequest(request(operation.ExecutionModeAsync,true,false).Operation);fp,_:=fingerprint(snapshot);prepared,_:=planner.prepare(context.Background(),planInput{Name:snapshot.Name,Class:snapshot.Class,DeviceID:snapshot.DeviceID,Parameters:snapshot.Parameters,MainPlanID:"plan"});payload,_:=encodeTaskPayload(taskPayload{Version:1,Request:snapshot,RequestFingerprint:fp,RequestID:"req",MainPlanID:"plan",MainPlanSHA256:prepared.MainHash});value:=task.Persisted{Task:task.Task{ID:"task",Operation:snapshot.Name,TargetID:"device",ExecutionMode:snapshot.ExecutionMode,Payload:payload},DryRun:true};audits.values["task"]=audit.Record{ID:"task"};result,err:=executor.Execute(context.Background(),value);if err!=nil||result.Status!=task.StatusSuccess||factory.opens!=0{t.Fatalf("result=%+v err=%v opens=%d",result,err,factory.opens)}}
func TestSaveFailureBecomesPartialSuccess(t *testing.T){planner,_,audits:=setup(t);factory:=&factoryStub{failSave:true};guard,_:=concurrency.NewController(5);executor,_:=NewExecutor(planner,audits,factory,guard);snapshot:=snapshotRequest(request(operation.ExecutionModeAsync,false,true).Operation);fp,_:=fingerprint(snapshot);prepared,_:=planner.prepare(context.Background(),planInput{Name:snapshot.Name,Class:snapshot.Class,DeviceID:snapshot.DeviceID,Parameters:snapshot.Parameters,SaveConfig:true,MainPlanID:"main",SavePlanID:"save"});payload,_:=encodeTaskPayload(taskPayload{Version:1,Request:snapshot,RequestFingerprint:fp,RequestID:"req",MainPlanID:"main",MainPlanSHA256:prepared.MainHash,SavePlanID:"save",SavePlanSHA256:prepared.SaveHash});value:=task.Persisted{Task:task.Task{ID:"task",Operation:snapshot.Name,TargetID:"device",ExecutionMode:snapshot.ExecutionMode,Payload:payload},SaveConfig:true};audits.values["task"]=audit.Record{ID:"task"};result,err:=executor.Execute(context.Background(),value);if err!=nil||result.Status!=task.StatusPartialSuccess||result.ErrorCode!=string(apperror.CodeConfigSaveFailed){t.Fatalf("result=%+v err=%v",result,err)}}
func TestAuditCompletionFailureDowngradesConfigSuccess(t *testing.T){planner,_,audits:=setup(t);audits.failComplete=true;guard,_:=concurrency.NewController(5);executor,_:=NewExecutor(planner,audits,&factoryStub{},guard);snapshot:=snapshotRequest(request(operation.ExecutionModeAsync,true,false).Operation);fp,_:=fingerprint(snapshot);prepared,_:=planner.prepare(context.Background(),planInput{Name:snapshot.Name,Class:snapshot.Class,DeviceID:snapshot.DeviceID,Parameters:snapshot.Parameters,MainPlanID:"plan"});payload,_:=encodeTaskPayload(taskPayload{Version:1,Request:snapshot,RequestFingerprint:fp,RequestID:"req",MainPlanID:"plan",MainPlanSHA256:prepared.MainHash});value:=task.Persisted{Task:task.Task{ID:"task",Operation:snapshot.Name,TargetID:"device",ExecutionMode:snapshot.ExecutionMode,Payload:payload},DryRun:true};result,err:=executor.Execute(context.Background(),value);if err!=nil||result.Status!=task.StatusPartialSuccess||result.ErrorCode!=string(apperror.CodeAuditUnavailable){t.Fatalf("result=%+v err=%v",result,err)}}
func TestHighRiskRequiresConfirmation(t *testing.T){if err:=enforceRisk(pluginapi.RiskHigh,false);!apperror.IsCode(err,apperror.CodeRiskConfirmationRequired){t.Fatalf("error=%v",err)};if err:=enforceRisk(pluginapi.RiskHigh,true);err!=nil{t.Fatal(err)};if err:=enforceRisk(pluginapi.RiskBlocked,true);!apperror.IsCode(err,apperror.CodeDangerousCommandBlocked){t.Fatalf("blocked=%v",err)}}
func TestIdempotencyReplayAndConflict(t *testing.T){planner,tasks,audits:=setup(t);queue:=&queueStub{repo:tasks};service:=newTestService(tasks,audits,planner,queue,Config{});ids:=[]string{"task-idem","plan-idem"};service.ids=func()(string,error){id:=ids[0];ids=ids[1:];return id,nil};first:=request(operation.ExecutionModeAsync,false,false);first.Operation.IdempotencyKey="same-key";created,err:=service.Submit(context.Background(),first);if err!=nil{t.Fatal(err)};replayed,err:=service.Submit(context.Background(),first);if err!=nil||!replayed.IdempotentReplay||replayed.Task.ID!=created.Task.ID||queue.calls!=1{t.Fatalf("replayed=%+v err=%v calls=%d",replayed,err,queue.calls)};conflict:=first;conflict.Operation.Parameters=map[string]any{"message":"different"};if _,err:=service.Submit(context.Background(),conflict);!apperror.IsCode(err,apperror.CodeIdempotencyConflict){t.Fatalf("conflict=%v",err)}}
func TestSensitivePlanIsRedactedButHasHash(t *testing.T){view:=redactPlan(pluginapi.ExecutionPlan{PlanID:"plan",DeviceID:"device",Vendor:pluginapi.VendorHuawei,PluginName:"test-plugin",PluginVersion:"1.0.0",Operation:"configuration.echo",Class:pluginapi.ClassConfig,RiskLevel:pluginapi.RiskMedium,Commands:[]pluginapi.PlannedCommand{{Sequence:1,Text:"secret-command password=abc",Sensitive:true,Timeout:time.Second}}});if len(view.Commands)!=1||view.Commands[0].Command!="<redacted>"||view.Commands[0].CommandSHA256==""{t.Fatalf("view=%+v",view)};encoded,_:=json.Marshal(view);if strings.Contains(string(encoded),"secret-command password=abc"){t.Fatalf("leaked=%s",encoded)}}
